### ISSUE TITLE
"Wrong" colors on sidebars.

### ISSUE THREAD

**Issue by Senjinx** [dotKom/jubileum#3]
Try to use #f1951a for orange and #004b80 for blue. These match the logo, although not the colors on the wiki. On this page it looks a lot smoother.

**Comment by hernil** [comment]
Colormaster is @tePose. I'm quite neutral to the whole thing 
¯\_(ツ)_/¯

**Comment by Senjinx** [comment]
![ny](https://cloud.githubusercontent.com/assets/3707747/18632766/5e4ef758-7e79-11e6-8eff-11c07d139a02.png)

The new colors match our logo. 

edit: retard grammatical error.

**Comment by melwil** [comment]
> The new colors matches our logo.

match\* since we're being picky.
